apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: production
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: satish680/fullstack:practice
        ports:
        - containerPort: 80
        env:
         - name: MY_SECRET
           valueFrom:
             secretKeyRef:
               name: secret-basic-auth
               key: MY_SECRET
