name: Continuous Deployment Pipeline

on:
  push:
    branches: 
     main

jobs:
  CD:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: | 
           docker build -t fullstack_practice codebase/rdicidr-0.1.0/.
           docker login
           docker tag fullstack_practice:latest satish680/fullstack:practice
           docker push satish680/fullstack:practice
           cd k8
           kubectl apply -f deployment.yml
           kubectl apply -f service.yml
           kubectl apply -f ingress.yml